source "https://rubygems.org"

gem "fastlane"
gem "aws-sdk-s3", ">= 1.208.0"
gem "faraday", ">= 1.10.5", "< 2.0"
gem "rexml", ">= 3.4.2"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
