name: Test pull request
concurrency: test-prq-app

on:
  pull_request:
    paths:
      - app/**

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make env
        working-directory: app/
        run: |
          echo "${{ secrets.DOTENV }}" > .env

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        working-directory: app/
        run: flutter pub get

      - name: Run analyzer
        working-directory: app/
        run: flutter analyze

      - name: Run unit tests
        working-directory: app/
        run: flutter test --coverage

      - name: Upload to code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: app/coverage/lcov.info
