name: Build and release app
concurrency:
  cancel-in-progress: true
  group: build-app

on:
  workflow_call:
    inputs:
      tag_name:
        type: string
        description: 'Tag name'
        required: true
      lane:
        type: string
        description: "Fastlane lane"
        required: true
        default: "beta"
    secrets:
      DOTENV:
        description: '.env file content'
        required: true
      ANDROID_KEYSTORE_BASE64:
        description: 'Android keystore base64'
        required: true
      ANDROID_KEYSTORE_PASSWORD:
        description: 'Android keystore password'
        required: true
      ANDROID_KEY_ALIAS:
        description: 'Android key alias'
        required: true
      GOOGLE_PLAY_SERVICE_JSON:
        description: 'Google Play service JSON'
        required: true
      TEAM_ID:
        description: 'Apple Team ID'
        required: true
      ITC_TEAM_ID:
        description: 'Apple ITC Team ID'
        required: true
      FASTLANE_USER_APPLE:
        description: 'Apple Fastlane user'
        required: true
      FASTLANE_PASSWORD_APPLE:
        description: 'Apple Fastlane password'
        required: true
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD:
        description: 'Apple Fastlane application specific password'
        required: true
      FASTLANE_SESSION:
        description: 'Apple Fastlane session'
        required: true
      MATCH_PASSWORD:
        description: 'Apple Match password'
        required: true
      MATCH_KEYCHAIN_NAME:
        description: 'Apple Match keychain name'
        required: true
      MATCH_KEYCHAIN_PASSWORD:
        description: 'Apple Match keychain password'
        required: true
      DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS:
        description: 'Apple Deliver ITMSTRANSPORTER additional upload parameters'
        required: true
        
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      lane:
        description: "Fastlane lane"
        required: true
        default: "beta"
        type: choice
        options:
          - internal
          - alpha
          - beta
          - promote_to_production
          - production

jobs:
  test:
    uses: ./.github/workflows/test-app.yaml
    secrets: inherit

  build:
    needs: ["test"]
    environment: production
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make env
        working-directory: app/
        run: |
          echo "${{ secrets.DOTENV }}" > .env

      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        working-directory: app/
        run: flutter pub get

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        working-directory: app/
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: app/android

      - name: Download bundle dependencies (android)
        working-directory: app/android
        run: |
          gem install bundler:2.3.26
          bundle config path vendor/bundle
          bundle install

      - name: Download bundle dependencies (ios)
        if: false # apple app store currently disabled
        working-directory: app/ios
        run: |
          gem install bundler:2.3.26
          bundle config path vendor/bundle
          bundle install

      - name: Release to Google Play (${{ github.event.inputs.lane || 'beta' }})
        working-directory: app/android
        env:
          SUPPLY_PACKAGE_NAME: org.radicand.app.cookbook
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_SERVICE_JSON }}
        run: |
          bundle exec fastlane run validate_play_store_json_key
          bundle exec fastlane ${{ github.event.inputs.lane || 'beta' }}

      - name: Release to Apple App Store (${{ github.event.inputs.lane || 'beta' }})
        if: false # apple app store currently disabled
        working-directory: app/ios
        env:
          SUPPLY_PACKAGE_NAME: org.radicand.app.cookbook
          TEAM_ID: ${{ secrets.TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER_APPLE }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD_APPLE }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS: ${{ secrets.DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS }}
        run: |
          pod install
          bundle exec fastlane ${{ github.event.inputs.lane || 'beta' }}
