name: Build and release faas
concurrency: build-faas

on:
  push:
    paths:
      - ".github/workflows/release-faas.yaml"
      - server/faas/*/**'
  workflow_dispatch:
jobs:
  build:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup faas-cli
        run: curl -sSL https://cli.openfaas.com | sudo sh

      - name: Login to openfaas
        run: faas-cli login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} -g ${{ secrets.OPENFAAS_GATEWAY }}

      - name: Publish functions
        working-directory: ./server/faas
        env:
          REPO_PATH: ghcr.io/${{ github.repository_owner }}
          OPENFAAS_GATEWAY: ${{ secrets.OPENFAAS_GATEWAY }}
        run: faas-cli publish -f functions.yaml --platforms linux/arm64

      - name: Deploy functions
        working-directory: ./server/faas
        env:
          REPO_PATH: ghcr.io/${{ github.repository_owner }}
          OPENFAAS_GATEWAY: ${{ secrets.OPENFAAS_GATEWAY }}
        run: faas-cli deploy -f functions.yaml
