name: Build and release web
concurrency:
  cancel-in-progress: true
  group: build-web

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: 'Tag name'
        required: true
  workflow_call:
    inputs:
      tag_name:
        type: string
        description: 'Tag name'
        required: true
    secrets:
      DOTENV:
        description: '.env file content'
        required: true
      CR_PAT:
        description: 'GitHub Container Registry Personal Access Token'
        required: true
      KUBE_CONFIG:
        description: 'Kubeconfig'
        required: true
      KUBE_INGRESS_BASE_DOMAIN:
        description: 'Kube ingress base domain'
        required: true
jobs:
  build:
    environment:
      name: production
      url: https://${{ steps.envurl.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make env
        working-directory: app/
        run: |
          echo "${{ secrets.DOTENV }}" > .env

      - name: Extract version from pubspec
        id: tagdata
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' app/pubspec.yaml | awk -F+ '{print $1}'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/radicand/cookbookery-web
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=${{ steps.tagdata.outputs.result }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: radicand
          password: ${{ secrets.CR_PAT }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        working-directory: app/
        run: flutter pub get

      - name: Build web
        working-directory: app/
        run: flutter build web --release

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./app
          file: ./app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false

      - name: Extract env url
        id: envurl
        run: |
          echo "::set-output name=url::cookbookery-web.${{ secrets.KUBE_INGRESS_BASE_DOMAIN }}"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > .kubeconfig
          chmod og-rwx .kubeconfig

      - name: Deploy
        run: |
          helm upgrade cookbookery-web-production ./app/manifest/cookbook-web --install -n cookbook --set image.repository=ghcr.io/radicand/cookbookery-web --set image.tag=${{ steps.tagdata.outputs.result }} --set ingress.host=${{ steps.envurl.outputs.url }} --set CI_PROJECT_PATH_SLUG=${{ github.ref_name }} --set CI_ENVIRONMENT_SLUG=production
        env:
          KUBECONFIG: .kubeconfig

      - name: Delete packages older than 7 days (but keep at least 3 versions)
        uses: davahome/ghcr-cleanup@v1.1
        with:
          token: ${{ secrets.CR_PAT }}
          package: cookbookery-web
          owner: user
          minimum_days: 7
          keep_versions: 3
          delete_untagged: 1
          keep_versions_untagged: 3
