name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      api--tag_name: ${{ steps.release.outputs['server/hasura--tag_name']}}
      api--release_created: ${{ steps.release.outputs['server/hasura--release_created']}}
      app--tag_name: ${{ steps.release.outputs.app--tag_name}}
      app--release_created: ${{ steps.release.outputs.app--release_created}}
      faas--tag_name: ${{ steps.release.outputs['server/faas--tag_name']}}
      faas--release_created: ${{ steps.release.outputs['server/faas--release_created']}}
      web--tag_name: ${{ steps.release.outputs.app--tag_name}}
      web--release_created: ${{ steps.release.outputs.app--release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo '${{ toJson(steps.release.outputs) }}'

  release-api:
    if: ${{needs.release-please.outputs.api--release_created}}
    needs: release-please
    uses: ./.github/workflows/release-api.yaml
    secrets: inherit
    with:
      tag_name: ${{needs.release-please.outputs.api--tag_name}}
  
  release-app:
    if: ${{needs.release-please.outputs.app--release_created}}
    needs: release-please
    uses: ./.github/workflows/release-app.yaml
    secrets: inherit
    with:
      tag_name: ${{needs.release-please.outputs.app--tag_name}}
      lane: beta

  release-faas:
    if: ${{needs.release-please.outputs.faas--release_created}}
    needs: release-please
    uses: ./.github/workflows/release-faas.yaml
    secrets: inherit
    with:
      tag_name: ${{needs.release-please.outputs.faas--tag_name}}

  release-web:
    if: ${{needs.release-please.outputs.web--release_created}}
    needs: release-please
    uses: ./.github/workflows/release-web.yaml
    secrets: inherit
    with:
      tag_name: ${{needs.release-please.outputs.web--tag_name}}
