name: Build and release app
concurrency: build-app

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/release-app.yaml"
      - app/CHANGELOG.md
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "internal"
        type: choice
        options:
          - internal
          - alpha
          - beta
          - promote_to_production
          - production

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    environment: production
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make env
        working-directory: app/
        run: |
          echo "${{ secrets.DOTENV }}" > .env

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.0.4
          channel: "stable"

      - name: Install dependencies
        working-directory: app/
        run: flutter pub get

      - name: Run analyzer
        working-directory: app/
        run: flutter analyze

      - name: Run unit tests
        working-directory: app/
        run: flutter test --coverage

      - name: Upload to code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: app/coverage/lcov.info

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        working-directory: app/
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties

      # - name: Build bundle
      #   working-directory: app/
      #   run: flutter build appbundle

      # - name: Run integration tests
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     working-directory: app/
      #     target: google_apis
      #     api-level: 30
      #     script: flutter drive --driver=test_driver/main_test.dart --target integration_test/app_test.dart
      # - name: Upload Screenshoots
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Test result screenshots
      #     path: app/screenshots/*.png

      # - name: Upload AAB
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release-aab
      #     path: app/build/app/outputs/bundle/release/app-release.aab

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: app/android

      - name: Download bundle dependencies
        working-directory: app/android
        run: |
          gem install bundler:2.0.2
          bundle config path vendor/bundle
          bundle install

      - name: Release to Google Play (${{ github.event.inputs.lane || 'internal' }})
        working-directory: app/android
        env:
          SUPPLY_PACKAGE_NAME: org.radicand.app.cookbook
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_SERVICE_JSON }}
        run: |
          bundle exec fastlane run validate_play_store_json_key
          bundle exec fastlane ${{ github.event.inputs.lane || 'internal' }}
