name: Build and release app
concurrency: build-app

on:
  workflow_call:
    inputs:
      lane:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "beta"
        type: choice
        options:
          - internal
          - alpha
          - beta
          - promote_to_production
          - production

# Declare default permissions as read only.
permissions: read-all

jobs:
  test:
    environment: production
    runs-on: macos-latest
    steps:
      - uses: radicand/Cookbookery/.github/workflows/test-app.yaml@main
  build:
    environment: production
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make env
        working-directory: app/
        run: |
          echo "${{ secrets.DOTENV }}" > .env

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.10
          channel: "stable"

      - name: Install dependencies
        working-directory: app/
        run: flutter pub get

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        working-directory: app/
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: app/android

      - name: Download bundle dependencies
        working-directory: app/android
        run: |
          gem install bundler:2.0.2
          bundle config path vendor/bundle
          bundle install

      - name: Release to Google Play (${{ github.event.inputs.lane || 'internal' }})
        working-directory: app/android
        env:
          SUPPLY_PACKAGE_NAME: org.radicand.app.cookbook
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_SERVICE_JSON }}
        run: |
          bundle exec fastlane run validate_play_store_json_key
          bundle exec fastlane ${{ github.event.inputs.lane || 'internal' }}

      - name: Release to Apple App Store (${{ github.event.inputs.lane || 'beta' }})
        working-directory: app/ios
        env:
          SUPPLY_PACKAGE_NAME: org.radicand.app.cookbook
          TEAM_ID: ${{ secrets.TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER_APPLE }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD_APPLE }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS: ${{ secrets.DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS }}
        run: |
          pod install
          bundle exec fastlane ${{ github.event.inputs.lane || 'beta' }}
